### ISSUE TITLE
Update GoVPP info on FD.io & VPP docs websites

### ISSUE THREAD

**Issue by ondrej-fabry** [FDio/govpp#103]
This issue tracks progress of updating info about GoVPP project on official FD.io web sites.

## Description

The official web for the FD.io project (https://fd.io/) is lacking any info about the GoVPP sub-project and web for the VPP documentation (https://s3-docs.fd.io/vpp/master/developer/build-run-debug/) contains limited or outdated info. 

## TODO

Here are few places to start with:
- [x] mention [GoVPP Community Meetings](#46) under _Meetings_ @ https://fd.io/getinvolved/community/
- [x] add info for developers under _VPP Developer Resources_ @ https://fd.io/getinvolved/community/
- [x] mention [GoVPP Slack channel](https://fdio-project.slack.com/archives/C01905FGAQ0) under _Communication Channels_ @ https://fd.io/getinvolved/community/
- [x] mention GoVPP mailing list under _Mailing Lists_ @ https://fd.io/getinvolved/community/
- [x] update info under _Interfacing with VPP / Go api (govpp)_ @ https://s3-docs.fd.io/vpp/23.02/interfacing/go/index.html
- [x] add link to GoVPP to top navigation bar under _Documentation_ @ https://fd.io/

**Comment by Neilblaze** [comment]
@ondrej-fabry Is this open to contributions?

**Comment by Neilblaze** [comment]
Thanks! Looking forward to it. @ondrej-fabry 😄 
Also, I'd be highly obliged if you can spare a moment to see [this](https://github.com/FDio/site/issues/122#issuecomment-1487279385).
